---
openingHours:
  start: "09:00"
  end: "12:00"
maxCapacityPerSlot: 40
slotInterval: 15
timezone: "Europe/Vienna"
waitlistEnabled: true
defaultSlots:
  - time: "09:00"
    capacity: 20
  - time: "09:30"
    capacity: 20
  - time: "10:00"
    capacity: 20
  - time: "10:30"
    capacity: 20
  - time: "11:00"
    capacity: 20
  - time: "11:30"
    capacity: 20
  - time: "12:00"
    capacity: 20
---
