---
openingHours:
  start: "09:00"
  end: "21:00"
maxCapacityPerSlot: 40
slotInterval: 15
timezone: "Europe/Vienna"
waitlistEnabled: true
defaultSlots:
  - time: "09:00"
    capacity: 40
  - time: "09:30"
    capacity: 40
  - time: "10:00"
    capacity: 40
  - time: "10:30"
    capacity: 40
  - time: "11:00"
    capacity: 40
  - time: "11:30"
    capacity: 40
  - time: "12:00"
    capacity: 40
  - time: "12:30"
    capacity: 40
  - time: "13:00"
    capacity: 40
  - time: "13:30"
    capacity: 40
  - time: "14:00"
    capacity: 40
  - time: "14:30"
    capacity: 40
  - time: "15:00"
    capacity: 40
  - time: "15:30"
    capacity: 40
  - time: "16:00"
    capacity: 40
  - time: "16:30"
    capacity: 40
  - time: "17:00"
    capacity: 40
  - time: "17:30"
    capacity: 40
  - time: "18:00"
    capacity: 40
  - time: "18:30"
    capacity: 40
  - time: "19:00"
    capacity: 40
  - time: "19:30"
    capacity: 40
  - time: "20:00"
    capacity: 40
  - time: "20:30"
    capacity: 40
---
